os: linux
dist: bionic
services:
  - docker

language:
  - generic

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - willson@robotis.com

branches:
  only:
    - master

install:
  - git clone --quiet --depth 1 https://github.com/ROBOTIS-Will/ros2ci.git .ros2ci

jobs:
  include:
    - name: "[Dashing]"
      env: ROS_DISTRO="dashing"
    - name: "[Eloquent]"
      env: ROS_DISTRO="eloquent"
    - name: "[Foxy]"
      env: ROS_DISTRO="foxy"

script: .ros2ci/travis.bash
