name: Foxy-CI-Lint

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ ros2, ros2-devel, foxy-devel ]
  pull_request:
    branches: [ ros2, ros2-devel, foxy-devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ros_ci_focal:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@0.1.2
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: turtlebot3_simulations
          target-ros2-distro: foxy
          vcs-repo-file-url: https://raw.githubusercontent.com/ROBOTIS-Will/turtlebot3_simulations/foxy-devel/turtlebot3_simulations_ci.repos
  ament_lint_foxy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, flake8, pep257, xmllint]
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@v0.1
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: ${{ matrix.distribution }}
          linter: foxy
          package-name: 
            turtlebot3_simulations
            turtlebot3_fake_node
            turtlebot3_gazebo